function runHelp({ packageJson, args }) {
  // Parse --advanced flag
  const showAdvanced = (args || []).includes('--advanced');

  console.log(`${packageJson.name} v${packageJson.version}`);
  console.log('');
  console.log('Knowledge Base CLI');
  console.log('https://williamduong.github.io/project-knowledge-base-template/');
  console.log('');

  if (!showAdvanced) {
    // Basic mode - only 4 core lifecycle commands
    console.log('Usage (core commands):');
    console.log('  kbx help [--advanced]');
    console.log('  kbx init [--mode private-git|tracked] [--target <path>] [--brand <name>] [--yes]');
    console.log('  kbx update [--accept-baseline] [--refresh-prompts]');
    console.log('  kbx ide <enable|disable> [--json] [--dry-run]');
    console.log('  kbx maintain [--accept-baseline] [--fast]');
    console.log('  kbx status [--json]');
    console.log('  kbx impact <doc-or-code> [--depth=N] [--json]');
    console.log('  kbx scan [--recursive] [--depth=N] [--json]');
    console.log('  kbx next [--json]');
    console.log('  kbx verify <doc> [--json]   |   kbx verify --all [--json]');
    console.log('  kbx baseline show [--json]   |   kbx baseline set <sha|--to-head> [--yes] [--json]');
    console.log('  kbx release init [--ignore-prerelease|--include-prerelease] [--json]');
    console.log('  kbx release tag <version> --summary=... [--json]');
    console.log('  kbx release list [--json]   |   kbx release show <version> [--json]');
    console.log('  kbx release notes <version> [--from=<tag>] [--output=<path>] [--format=md|json] [--json]');
    console.log('  kbx release run [--bump=patch|minor|major] [--target=npm|gh|all] [--from=<tag>] [--yes] [-f|--file <path>] [--json]');
    console.log('  kbx release plan [--bump=patch|minor|major] [--target=npm|gh|all] [--from=<tag>] [-f|--file <path>] [--json]');
    console.log('  kbx release init-pipeline [--template=npm-package|docs-only|custom] [--yes] [--json]');
    console.log('  kbx plan --request "..." --dry-run [--json]');
    console.log('  kbx intent create [<id>] [--mode=quick|full] [--change-type=<type>] [--yes] [--json]');
    console.log('  kbx intent status [<id>] [--json]');
    console.log('  kbx intent list [--json]');
    console.log('  kbx intent apply <id> [--release] [--yes] [--json]');
    console.log('  kbx intent cancel <id> [--yes] [--json]');
    console.log('  kbx intent suggest-lessons [--json]');
    console.log('  kbx chaos [--json] [--no-save] [--quiet] [--scan-src <dir>]');
    console.log('  kbx graph export [--lane=<rules|intents|source>] [--output=<path>] [--json]');
      console.log('  kbx graph export --format json --out .kbx-graph/latest.json [--json]');
      console.log('  kbx graph export --format json --out .kbx-graph/latest.json [--json]');
    console.log('  kbx graph lane <rules|intents|source> [--output=<path>] [--json]');
    console.log('  kbx graph check  [--json]');
    console.log('  kbx ontology <show|validate|audit|build> [options]');
    console.log('  kbx rules <lint|check|list> [options]');
    console.log('  kbx inspect --path <file-or-folder> [--json]');
    console.log('  kbx apply --request "..." (--dry-run|--execute --yes) [--json]');
    console.log('  kbx gate [--release] [--json]');
    console.log('  kbx dispatch --fixture <path> --dry-run [--json]');
    console.log('  kbx dispatch test --fixtures <dir> [--json]');
    console.log('  kbx dispatch select --fixture <path> [--mode diagnostic|execution] [--json]');
    console.log('  kbx dispatch ground --fixture <path> [--projected-chaos=<n>] [--active-intents=<n>] [--json]');
    console.log('  kbx dispatch verify-end --fixture <path> [--projected-chaos=<n>] [--json]');
    console.log('  kbx dispatch loop --fixture <path> [--max-attempts=2] [--target-outcome=pass|warn|fail] [--json]');
    console.log('  kbx extract <source-file> [--target-doc=<path>] [--apply=<output>] [--uncovered] [--model=<hint>] [--yes] [--json]');
    console.log('  kbx ingest <source-file> [--type=auto|text|pdf|image|docx|xlsx] [--json]');
    console.log('  kbx uninstall [--keep-ai-files] [--remove-hook] [--force]');
    console.log('  kbx workspace detect                    Scan for KBX project repos');
    console.log('  kbx workspace promote [--yes] [--json]  Create workspace registry from detected repos');
    console.log('  kbx workspace verify  [--json]          Drift-check workspace registry vs filesystem');
    console.log('');
    console.log('Core workflow:');
    console.log('  init       Install the KB template into a target workspace and create state.');
    console.log('             Auto-detects mode (private-git if .git exists, tracked otherwise).');
    console.log('             If KB already exists, prompts for rerun confirmation.');
    console.log('             --yes             Skip rerun confirmation prompt.');
    console.log('             --skip-adapters   Skip generating AI IDE adapter files.');
    console.log('             --install-hooks   Install a pre-commit hook that runs kbx doctor.');
    console.log('             --skip-bootstrap  Skip initial placeholder filling after init.');
    console.log('             --skip-index      Skip initial KB index summary generation.');
    console.log('  update     Refresh KB state after sync and reconcile template version metadata.');
    console.log('             Use --accept-baseline to stamp current HEAD as the new baseline.');
    console.log('             Use --refresh-prompts to overwrite .github/agents/kbx.agent.md,');
    console.log('             .github/prompts/kbx-*.prompt.md and .github/hooks/revision-state-guard.json');
    console.log('             with the latest template versions (does not touch state.json).');
    console.log('  maintain   One-command maintenance pipeline.');
    console.log('             Default: sync + doc:gate (if available) + test --all + doctor --strict.');
    console.log('             --fast            Quick mode: skips doc:gate, sampled test, non-strict doctor.');
    console.log('  ide        Manage IDE integration blocks without touching state by hand.');
    console.log('             enable            Inject kbx-managed block and set state.ideIntegration.enabled=true.');
    console.log('             disable           Remove injected blocks from tracked targets and disable integration.');
    console.log('             --dry-run         Preview targets for enable only.');
    console.log('             --json            Machine-readable output.');
    console.log('  status     Report KB install state (fresh / healthy / partial) and key state fields.');
    console.log('             --json            Machine-readable output.');
    console.log('  uninstall  Remove KB content and generated AI helper files.');
    console.log('             Use --keep-ai-files to keep AGENTS/prompt files.');
    console.log('             Use --remove-hook to remove kbx-managed pre-commit hook.');
    console.log('');
    console.log('Other commands are available for power users.');
    console.log('Run "kbx help --advanced" to see all commands.');
    console.log('Next step: Use /kbx-ask with Copilot Chat to query your KB, or /kbx-run to execute the plan');
    return;
  }

  // Advanced mode - show all commands
  console.log('Usage:');
  console.log('  kbx help [--advanced]');
  console.log('  kbx init [--mode private-git|tracked] [--target <path>] [--brand <name>] [--yes]');
  console.log('          [--skip-adapters] [--install-hooks] [--skip-bootstrap] [--skip-index]');
  console.log('  kbx maintain [--accept-baseline] [--fast]');
  console.log('  kbx bootstrap [--dry-run] [--no-fill-placeholders]');
  console.log('  kbx index [--watch]');
  console.log('  kbx questions [--print] [--all-states] [--chat] [--batch <n>] [--batch-size <n>]');
  console.log('  kbx mark --file <relative-md-path> --state <template|autofilled|needs-review|verified|blocked>');
  console.log('  kbx normalize-state [--dry-run]');
  console.log('  kbx migrate --to=<version> --dry-run [--json]');
  console.log('  kbx migrate --to=<version> --dry-run [--json]');
  console.log('  kbx bootstrap-api [--dry-run]');
  console.log('  kbx plan list');
  console.log('  kbx plan add "<description>" [--owner <name>] [--priority P0|P1|P2]');
  console.log('  kbx plan --request "..." --dry-run [--json]');
  console.log('  kbx show [--backup-existing]');
  console.log('  kbx hide [--restore-backup]');
  console.log('  kbx test [--sample <count>] [--all]');
  console.log('  kbx sync [--accept-baseline]');
  console.log('  kbx update [--accept-baseline] [--refresh-prompts]');
  console.log('  kbx ide <enable|disable> [--json] [--dry-run]');
  console.log('  kbx doctor [--json] [--strict]');
  console.log('  kbx status [--json]');
  console.log('  kbx impact <doc-or-code> [--depth=N] [--json]');
  console.log('  kbx scan [--recursive] [--depth=N] [--json]');
  console.log('  kbx next [--json]');
  console.log('  kbx verify <doc> [--json]');
  console.log('  kbx verify --all [--json]');
  console.log('  kbx baseline show [--json]');
  console.log('  kbx baseline set <sha> [--yes] [--json]');
  console.log('  kbx baseline set --to-head [--yes] [--json]');
  console.log('  kbx release init [--ignore-prerelease|--include-prerelease] [--json]');
  console.log('  kbx release tag <version> --summary=... [--json]');
  console.log('  kbx release list [--json]');
  console.log('  kbx release show <version> [--json]');
  console.log('  kbx release notes <version> [--from=<tag>] [--output=<path>] [--format=md|json] [--json]');
  console.log('  kbx release run [--bump=patch|minor|major] [--target=npm|gh|all] [--from=<tag>] [--yes] [-f|--file <path>] [--json]');
  console.log('  kbx release plan [--bump=patch|minor|major] [--target=npm|gh|all] [--from=<tag>] [-f|--file <path>] [--json]');
  console.log('  kbx release init-pipeline [--template=npm-package|docs-only|custom] [--yes] [--json]');
  console.log('  kbx intent create [<id>] [--mode=quick|full] [--change-type=<type>] [--yes] [--json]');
  console.log('  kbx intent status [<id>] [--json]');
  console.log('  kbx intent list [--json]');
  console.log('  kbx intent apply <id> [--release] [--yes] [--json]');
  console.log('  kbx intent cancel <id> [--yes] [--json]');    console.log('  kbx chaos [--json] [--no-save] [--quiet] [--scan-src <dir>]');  console.log('  kbx uninstall [--keep-ai-files] [--remove-hook] [--force]');
  console.log('  kbx intent suggest-lessons [--json]');
  console.log('  kbx extract <source-file> [--target-doc=<path>] [--apply=<output>] [--uncovered] [--model=<hint>] [--yes] [--json]');
  console.log('  kbx ingest <source-file> [--type=auto|text|pdf|image|docx|xlsx] [--json]');
  console.log('  kbx ontology <show|validate|audit|build> [--type auto|intent|contract] [--json]');
  console.log('  kbx rules lint [--json]');
  console.log('  kbx rules check <rule-id> [--json]');
  console.log('  kbx rules list [--json]');
  console.log('  kbx inspect --path <file-or-folder> [--json]');
  console.log('  kbx apply --request "..." (--dry-run|--execute --yes) [--json]');
  console.log('  kbx gate [--release] [--json]');
  console.log('  kbx dispatch --fixture <path> --dry-run [--json]');
  console.log('  kbx dispatch test --fixtures <dir> [--json]');
  console.log('  kbx dispatch select --fixture <path> [--mode diagnostic|execution] [--json]');
  console.log('  kbx dispatch ground --fixture <path> [--projected-chaos=<n>] [--active-intents=<n>] [--json]');
  console.log('  kbx dispatch verify-end --fixture <path> [--projected-chaos=<n>] [--json]');
  console.log('  kbx dispatch loop --fixture <path> [--max-attempts=2] [--target-outcome=pass|warn|fail] [--json]');
  console.log('  kbx version');
  console.log('');
  console.log('Implemented commands:');
  console.log('  help       Show usage and package information.');
  console.log('  init       Install the KB template into a target workspace and create state.');
  console.log('             If KB already exists, prompts for rerun confirmation.');
  console.log('             --yes             Skip rerun confirmation prompt.');
  console.log('             --skip-adapters   Skip generating AI IDE adapter files.');
  console.log('             --install-hooks   Install a pre-commit hook that runs kbx doctor.');
  console.log('             --skip-bootstrap  Skip initial placeholder filling after init.');
  console.log('             --skip-index      Skip initial KB index summary generation.');
  console.log('  maintain   Run sync/test/doctor maintenance pipeline in one command.');
  console.log('             Default: sync + doc:gate (if available) + test --all + doctor --strict.');
  console.log('             --fast            Quick mode: skips doc:gate, sampled test, non-strict doctor.');
  console.log('             --accept-baseline Pass-through to sync baseline acceptance.');
  console.log('  ide        Manage kbx-managed IDE integration blocks.');
  console.log('             enable            Inject into detected targets and set state.ideIntegration enabled.');
  console.log('             disable           Remove from tracked targets and disable integration.');
  console.log('             --dry-run         Preview enable targets only.');
  console.log('             --json            Machine-readable output.');
  console.log('  bootstrap  Scan source code and generate unverified stub docs for');
  console.log('             03-architecture, 05-backend, 06-api, 07-database, 09-operations.');
  console.log('             --dry-run         Preview create/update/skip actions.');
  console.log('             --no-fill-placeholders  Do not replace existing template placeholders.');
  console.log('  index      Build KB index summary (doc counts, placeholder counts, source signals).');
  console.log('             --watch           Rebuild every 10s for background indexing workflow.');
  console.log('  questions  Generate intake questions from unresolved placeholders/TODOs.');
  console.log('             --print           Print top questions for immediate AI chat Q&A.');
  console.log('             --chat            Print interactive 5-question intake batch for chat flow.');
  console.log('             --batch <n>       Choose batch number when --chat is enabled.');
  console.log('             --batch-size <n>  Set batch size (default 5, max 20).');
  console.log('             Default state order: needs-review -> autofilled -> template.');
  console.log('             --all-states      Include all kb_state values (default filters review/autofill/template).');
  console.log('  mark       Set kb_state for a KB markdown file without renaming files.');
  console.log('  normalize-state  Assign kb_state for docs that are currently unset.');
  console.log('             --dry-run         Preview state assignment without modifying files.');
  console.log('  migrate    Preview v2.4 intent schema migration for legacy intent metadata.');
  console.log('             --to=<version>    Required target schema version, e.g. v2.4.0.');
  console.log('             --dry-run         Required in this slice; prints folder-first migration plan only.');
  console.log('             --json            Machine-readable migration preview.');
  console.log('  bootstrap-api  Generate endpoint docs from route/controller annotations.');
  console.log('             --dry-run         Preview endpoint doc creation/update only.');
  console.log('  plan       Manage the KB strategic backlog (strategic-backlog.md).');
  console.log('             list              Show pending and done plan items.');
  console.log('             add "<text>"      Append a new todo item with auto-incremented ID.');
  console.log('  show       Expose a hidden KB mount into the workspace (private-git mode).');
  console.log('             Use --backup-existing to move a real directory out of the way safely.');
  console.log('  hide       Remove the visible KB mount while keeping canonical content (private-git mode).');
  console.log('             Use --restore-backup to restore a previous backup directory.');
  console.log('  test       Run deterministic KB integrity and drift checks.');
  console.log('             --all            Validate frontmatter on all indexed markdown docs.');
  console.log('  sync       Collect drift evidence, map source_of_truth changes, and update queue/report.');
  console.log('             Use --accept-baseline to stamp HEAD as new baseline after review.');
  console.log('  update     Sync first, then refresh template version state.');
  console.log('             Use --accept-baseline to propagate sync baseline acceptance.');
  console.log('  doctor     Quick publish-readiness checks (node/git/link/hooks).');
  console.log('             Use --json for machine-readable CI output.');
  console.log('             Use --strict to exit with code 1 on WARN (hard CI gate).');
  console.log('  status     Report KB install state and key state.json fields.');
  console.log('             Classification: fresh | healthy | partial.');
  console.log('             --json           Machine-readable JSON.');
  console.log('  impact     Recursive impact analysis (graphology in-memory).');
  console.log('             Traverses related_strong + binds_to (depth-1). related_weak displayed only.');
  console.log('             --depth=N        Override default depth (capped at impact.maxDepth).');
  console.log('             --json           Machine-readable JSON.');
  console.log('  scan       Scan git diff (baseline..HEAD), bind code changes to docs, write impact.json.');
  console.log('             --recursive      Expand related_strong neighbours into transitive_impacted[].');
  console.log('             --depth=N        Recursive depth (capped at impact.maxDepth, default impact.defaultDepth).');
  console.log('             --json           Machine-readable JSON.');
  console.log('  next       Summarize the next most useful KB actions for a solo workflow.');
  console.log('             Prioritizes: drift unresolved -> review backlog -> missing critical docs -> stale source mirror.');
  console.log('             --json           Machine-readable JSON.');
  console.log('  verify     Bump last_verified + last_verified_commit (current HEAD) for a doc.');
  console.log('             Clears matching entries from impact.json on success.');
  console.log('             --all            Verify every doc currently in impact.json (atomic on failure).');
  console.log('             --json           Machine-readable JSON.');
  console.log('  baseline   Inspect or set the source git baseline in state.json.');
  console.log('             show             Print baseline + capture metadata.');
  console.log('             set <sha>        Set baseline (interactive confirm; --yes to skip).');
  console.log('             set --to-head    Set baseline to current git HEAD.');
  console.log('  release    Manage KB release catalog metadata in .kb/catalog.json.');
  console.log('             init             Build catalog from git tags (v*), skipping prerelease by default.');
  console.log('             tag <version>    Append one release from an existing git tag (requires --summary).');
  console.log('             list             List catalog releases (current marked with *).');
  console.log('             show <version>   Show one release entry in detail.');
  console.log('             notes <version>  Generate release notes from git range (previous..version).');
  console.log('                               --from=<tag> overrides previous release detection.');
  console.log('                               --output=<path> writes file; default prints to stdout.');
  console.log('                               --format=md|json (default md; --json implies json payload).');
  console.log('             run              Execute release pipeline (.kb/release-pipeline.yaml by default).');
  console.log('                               --yes bypasses per-step confirm gates.');
  console.log('                               -f|--file <path> selects pipeline file.');
  console.log('                               --bump=patch|minor|major, --target=npm|gh|all, --from=<tag>.');
  console.log('             plan             Dry-run alias of run (prints resolved step plan, no execution).');
  console.log('             init-pipeline    Copy a starter pipeline into .kb/release-pipeline.yaml.');
  console.log('                               --template=npm-package|docs-only|custom (default npm-package).');
  console.log('                               --yes overwrites existing pipeline file.');
  console.log('  intent     Manage intent workspaces for structured KB changes.');
  console.log('             create [<id>]    Create a new intent workspace.');
  console.log('                               Suggests ID from git branch; prompts to confirm/edit.');
  console.log('                               --mode=quick|full (default quick).');
  console.log('                               --change-type=docs|feature|fix|refactor|governance.');
  console.log('                               --yes  Accept suggested ID without prompt.');
  console.log('             status [<id>]    Show status of one or all active intents.');
  console.log('                               With <id>: staged files, warnings, plan/impact presence.');
  console.log('                               Without <id>: summary list of all active intents.');
  console.log('             list             List active intents with status/mode/staged count as a table.');
  console.log('                               Pager activates automatically when output exceeds terminal height.');
  console.log('             apply <id>       Write staged files to KB core, archive workspace, optionally run release.');
  console.log('                               --release  Trigger release pipeline after apply (apply first, then release).');
  console.log('                               --yes      Skip confirmation prompt.');
  console.log('             cancel <id>      Delete an active intent workspace (irreversible; --yes to skip confirm).');
  console.log('  extract    Generate a documentation extraction prompt for a source file.');
  console.log('             <source-file>    Source file to analyse.');
  console.log('             --target-doc=<p> Target KB doc to update.');
  console.log('             --apply=<file>   Write prompt output to this file (requires --target-doc).');
  console.log('             --uncovered      List source files with no linked doc.');
  console.log('             --model=<hint>   Model hint appended to prompt header.');
  console.log('             --yes            Skip confirmation prompts.');
  console.log('  ingest     Register a source file into the KB ingestion pipeline.');
  console.log('             <source-file>    File to ingest (text/pdf/image/docx/xlsx).');
  console.log('             --type=<t>       Force type: auto (default), text, pdf, image, docx, xlsx.');
  console.log('             Writes a structured payload to .kb/ingestion/<id>.json.');
  console.log('             Text files are chunked immediately (ready); binary types produce a parser stub.');
  console.log('  chaos      Compute KB Chaos Coefficient — unified AI agent confidence index.');
  console.log('             Aggregates technical debt, entropy, coverage gap, cognitive load,');
  console.log('             and instability into a single 0–100 score with level (stable →');
  console.log('             manageable → unstable → chaotic). Saves snapshot to chaos-history.md.');
  console.log('             Detects chaos spikes (Δ≥10 pts) vs previous snapshot.');
  console.log('             Produces forward estimates for planned versions.');
  console.log('             --scan-src <dir>  Enhance accuracy with actual LOC/coupling data.');
  console.log('             --no-save         Skip writing snapshot to chaos-history.md.');
  console.log('             --quiet           Print "<score> <level>" only.');
  console.log('             --json            Machine-readable JSON output.');
  console.log('  graph      Export or check KB entity/relation graph (v1.9 mini).');
  console.log('             export            Write JSONL of entities + relations (deterministic).');
  console.log('                               --output=<path>  Write to file; default stdout.');
  console.log('             check             Run basic consistency checks:');
  console.log('                               missing-node-reference, invalid-relation-type, duplicate-entity-id.');
  console.log('             --json            Machine-readable JSON output.');
  console.log('  ontology   Validate and inspect ontology lifecycle contracts.');
  console.log('             show              Print schema + lifecycle + guard contract.');
  console.log('             validate          Validate intent or ontology contract fixtures.');
  console.log('             audit             Audit natural-language payload against governed glossary.');
  console.log('             build             Compile deterministic ontology artifact.');
  console.log('  uninstall  Remove KB installation from the workspace.');
  console.log('             --keep-ai-files  Keep AGENTS/prompt files at repo root.');
  console.log('             --remove-hook    Remove kbx-managed .git/hooks/pre-commit.');
  console.log('             --force          In private-git mode, delete non-link knowledge-base directory.');
}

module.exports = {
  runHelp,
};